package bnConst

const (
	BNB                    = "BNB"
	BNBUSDT                = "BNBUSDT"
	BINANCE_FUTURE_BNBUSDT = "BINANCE_FUTURE_BNBUSDT"
	BINANCE_FUTURE_ETHUSDT = "BINANCE_FUTURE_ETHUSDT"
	BINANCE_FUTURE_ETHUSDC = "BINANCE_FUTURE_ETHUSDC"
)

const (
	TRAN_SPOT        = "SPOT"
	TRAN_USDT_FUTURE = "USDT_FUTURE"
	TRAN_COIN_FUTURE = "COIN_FUTURE"
)

const (
	ORDER_TRADE_UPDATE = "ORDER_TRADE_UPDATE"
	ACCOUNT_UPDATE     = "ACCOUNT_UPDATE"
	TRADE_LITE         = "TRADE_LITE"
)

const (
	USDT  = "USDT"
	FDUSD = "FDUSD"
	USDC  = "USDC"
)
