// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.14.0
// source: api/strategy/v1/strategy.proto

package strategyV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_OK                 ErrorCode = 0
	ErrorCode_INVALID_ARGUMENT   ErrorCode = 1
	ErrorCode_INTERNAL_ERROR     ErrorCode = 2
	ErrorCode_STRATEGY_NOT_FOUND ErrorCode = 3
	ErrorCode_AUTH_FAILED        ErrorCode = 4
	ErrorCode_INSTANCE_ID_EMPTY  ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
		1: "INVALID_ARGUMENT",
		2: "INTERNAL_ERROR",
		3: "STRATEGY_NOT_FOUND",
		4: "AUTH_FAILED",
		5: "INSTANCE_ID_EMPTY",
	}
	ErrorCode_value = map[string]int32{
		"OK":                 0,
		"INVALID_ARGUMENT":   1,
		"INTERNAL_ERROR":     2,
		"STRATEGY_NOT_FOUND": 3,
		"AUTH_FAILED":        4,
		"INSTANCE_ID_EMPTY":  5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_strategy_v1_strategy_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_strategy_v1_strategy_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{0}
}

type ServerReqBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestIp     string                 `protobuf:"bytes,1,opt,name=requestIp,proto3" json:"requestIp,omitempty"`        // 请求 IP
	InstanceId    uint32                 `protobuf:"varint,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`     // 策略实例 ID
	StrategyType  uint32                 `protobuf:"varint,3,opt,name=strategyType,proto3" json:"strategyType,omitempty"` // 策略类型(英文标识)
	StrategyName  string                 `protobuf:"bytes,4,opt,name=strategyName,proto3" json:"strategyName,omitempty"`  // 策略名称/描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerReqBase) Reset() {
	*x = ServerReqBase{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReqBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReqBase) ProtoMessage() {}

func (x *ServerReqBase) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReqBase.ProtoReflect.Descriptor instead.
func (*ServerReqBase) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *ServerReqBase) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

func (x *ServerReqBase) GetInstanceId() uint32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *ServerReqBase) GetStrategyType() uint32 {
	if x != nil {
		return x.StrategyType
	}
	return 0
}

func (x *ServerReqBase) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

type StrategyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonMeta    *ServerReqBase         `protobuf:"bytes,1,opt,name=commonMeta,proto3" json:"commonMeta,omitempty"`
	JsonData      string                 `protobuf:"bytes,2,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyReq) Reset() {
	*x = StrategyReq{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyReq) ProtoMessage() {}

func (x *StrategyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyReq.ProtoReflect.Descriptor instead.
func (*StrategyReq) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *StrategyReq) GetCommonMeta() *ServerReqBase {
	if x != nil {
		return x.CommonMeta
	}
	return nil
}

func (x *StrategyReq) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type CommonReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=strategyV1.ErrorCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	JsonData      string                 `protobuf:"bytes,3,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonReplay) Reset() {
	*x = CommonReplay{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReplay) ProtoMessage() {}

func (x *CommonReplay) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReplay.ProtoReflect.Descriptor instead.
func (*CommonReplay) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *CommonReplay) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *CommonReplay) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CommonReplay) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

var File_api_strategy_v1_strategy_proto protoreflect.FileDescriptor

const file_api_strategy_v1_strategy_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/strategy/v1/strategy.proto\x12\n" +
	"strategyV1\"\x95\x01\n" +
	"\rServerReqBase\x12\x1c\n" +
	"\trequestIp\x18\x01 \x01(\tR\trequestIp\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\rR\n" +
	"instanceId\x12\"\n" +
	"\fstrategyType\x18\x03 \x01(\rR\fstrategyType\x12\"\n" +
	"\fstrategyName\x18\x04 \x01(\tR\fstrategyName\"d\n" +
	"\vStrategyReq\x129\n" +
	"\n" +
	"commonMeta\x18\x01 \x01(\v2\x19.strategyV1.ServerReqBaseR\n" +
	"commonMeta\x12\x1a\n" +
	"\bjsonData\x18\x02 \x01(\tR\bjsonData\"g\n" +
	"\fCommonReplay\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.strategyV1.ErrorCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\bjsonData\x18\x03 \x01(\tR\bjsonData*}\n" +
	"\tErrorCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x01\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x02\x12\x16\n" +
	"\x12STRATEGY_NOT_FOUND\x10\x03\x12\x0f\n" +
	"\vAUTH_FAILED\x10\x04\x12\x15\n" +
	"\x11INSTANCE_ID_EMPTY\x10\x052\xdc\x01\n" +
	"\bStrategy\x12D\n" +
	"\rStartStrategy\x12\x17.strategyV1.StrategyReq\x1a\x18.strategyV1.CommonReplay\"\x00\x12E\n" +
	"\x0eUpdateStrategy\x12\x17.strategyV1.StrategyReq\x1a\x18.strategyV1.CommonReplay\"\x00\x12C\n" +
	"\fStopStrategy\x12\x17.strategyV1.StrategyReq\x1a\x18.strategyV1.CommonReplay\"\x00B\x0eZ\f.;strategyV1b\x06proto3"

var (
	file_api_strategy_v1_strategy_proto_rawDescOnce sync.Once
	file_api_strategy_v1_strategy_proto_rawDescData []byte
)

func file_api_strategy_v1_strategy_proto_rawDescGZIP() []byte {
	file_api_strategy_v1_strategy_proto_rawDescOnce.Do(func() {
		file_api_strategy_v1_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_strategy_v1_strategy_proto_rawDesc), len(file_api_strategy_v1_strategy_proto_rawDesc)))
	})
	return file_api_strategy_v1_strategy_proto_rawDescData
}

var file_api_strategy_v1_strategy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_strategy_v1_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_strategy_v1_strategy_proto_goTypes = []any{
	(ErrorCode)(0),        // 0: strategyV1.ErrorCode
	(*ServerReqBase)(nil), // 1: strategyV1.ServerReqBase
	(*StrategyReq)(nil),   // 2: strategyV1.StrategyReq
	(*CommonReplay)(nil),  // 3: strategyV1.CommonReplay
}
var file_api_strategy_v1_strategy_proto_depIdxs = []int32{
	1, // 0: strategyV1.StrategyReq.commonMeta:type_name -> strategyV1.ServerReqBase
	0, // 1: strategyV1.CommonReplay.code:type_name -> strategyV1.ErrorCode
	2, // 2: strategyV1.Strategy.StartStrategy:input_type -> strategyV1.StrategyReq
	2, // 3: strategyV1.Strategy.UpdateStrategy:input_type -> strategyV1.StrategyReq
	2, // 4: strategyV1.Strategy.StopStrategy:input_type -> strategyV1.StrategyReq
	3, // 5: strategyV1.Strategy.StartStrategy:output_type -> strategyV1.CommonReplay
	3, // 6: strategyV1.Strategy.UpdateStrategy:output_type -> strategyV1.CommonReplay
	3, // 7: strategyV1.Strategy.StopStrategy:output_type -> strategyV1.CommonReplay
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_strategy_v1_strategy_proto_init() }
func file_api_strategy_v1_strategy_proto_init() {
	if File_api_strategy_v1_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_strategy_v1_strategy_proto_rawDesc), len(file_api_strategy_v1_strategy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_strategy_v1_strategy_proto_goTypes,
		DependencyIndexes: file_api_strategy_v1_strategy_proto_depIdxs,
		EnumInfos:         file_api_strategy_v1_strategy_proto_enumTypes,
		MessageInfos:      file_api_strategy_v1_strategy_proto_msgTypes,
	}.Build()
	File_api_strategy_v1_strategy_proto = out.File
	file_api_strategy_v1_strategy_proto_goTypes = nil
	file_api_strategy_v1_strategy_proto_depIdxs = nil
}
