// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.14.0
// source: api/strategy/v1/strategy.proto

package strategyV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Strategy_StartStrategy_FullMethodName  = "/strategyV1.Strategy/StartStrategy"
	Strategy_UpdateStrategy_FullMethodName = "/strategyV1.Strategy/UpdateStrategy"
	Strategy_StopStrategy_FullMethodName   = "/strategyV1.Strategy/StopStrategy"
)

// StrategyClient is the client API for Strategy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyClient interface {
	StartStrategy(ctx context.Context, in *StrategyReq, opts ...grpc.CallOption) (*CommonReplay, error)
	UpdateStrategy(ctx context.Context, in *StrategyReq, opts ...grpc.CallOption) (*CommonReplay, error)
	StopStrategy(ctx context.Context, in *StrategyReq, opts ...grpc.CallOption) (*CommonReplay, error)
}

type strategyClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyClient(cc grpc.ClientConnInterface) StrategyClient {
	return &strategyClient{cc}
}

func (c *strategyClient) StartStrategy(ctx context.Context, in *StrategyReq, opts ...grpc.CallOption) (*CommonReplay, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonReplay)
	err := c.cc.Invoke(ctx, Strategy_StartStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategy(ctx context.Context, in *StrategyReq, opts ...grpc.CallOption) (*CommonReplay, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonReplay)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) StopStrategy(ctx context.Context, in *StrategyReq, opts ...grpc.CallOption) (*CommonReplay, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonReplay)
	err := c.cc.Invoke(ctx, Strategy_StopStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyServer is the server API for Strategy service.
// All implementations must embed UnimplementedStrategyServer
// for forward compatibility.
type StrategyServer interface {
	StartStrategy(context.Context, *StrategyReq) (*CommonReplay, error)
	UpdateStrategy(context.Context, *StrategyReq) (*CommonReplay, error)
	StopStrategy(context.Context, *StrategyReq) (*CommonReplay, error)
	mustEmbedUnimplementedStrategyServer()
}

// UnimplementedStrategyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyServer struct{}

func (UnimplementedStrategyServer) StartStrategy(context.Context, *StrategyReq) (*CommonReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartStrategy not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategy(context.Context, *StrategyReq) (*CommonReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategy not implemented")
}
func (UnimplementedStrategyServer) StopStrategy(context.Context, *StrategyReq) (*CommonReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopStrategy not implemented")
}
func (UnimplementedStrategyServer) mustEmbedUnimplementedStrategyServer() {}
func (UnimplementedStrategyServer) testEmbeddedByValue()                  {}

// UnsafeStrategyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyServer will
// result in compilation errors.
type UnsafeStrategyServer interface {
	mustEmbedUnimplementedStrategyServer()
}

func RegisterStrategyServer(s grpc.ServiceRegistrar, srv StrategyServer) {
	// If the following call pancis, it indicates UnimplementedStrategyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Strategy_ServiceDesc, srv)
}

func _Strategy_StartStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).StartStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_StartStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).StartStrategy(ctx, req.(*StrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategy(ctx, req.(*StrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_StopStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).StopStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_StopStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).StopStrategy(ctx, req.(*StrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Strategy_ServiceDesc is the grpc.ServiceDesc for Strategy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Strategy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "strategyV1.Strategy",
	HandlerType: (*StrategyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartStrategy",
			Handler:    _Strategy_StartStrategy_Handler,
		},
		{
			MethodName: "UpdateStrategy",
			Handler:    _Strategy_UpdateStrategy_Handler,
		},
		{
			MethodName: "StopStrategy",
			Handler:    _Strategy_StopStrategy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/strategy/v1/strategy.proto",
}
