package execute

type OrderMode uint8

const (
	BUY_OPEN_LIMIT OrderMode = iota
	SELL_OPEN_LIMIT
	BUY_CLOSE_LIMIT
	SELL_CLOSE_LIMIT
	BUY_OPEN_LIMIT_MAKER
	SELL_OPEN_LIMIT_MAKER
	BUY_CLOSE_LIMIT_MAKER
	SELL_CLOSE_LIMIT_MAKER
	BUY_OPEN_MARKET
	SELL_OPEN_MARKET
)

func (s OrderMode) IsBuy() bool {
	switch s {
	case BUY_OPEN_LIMIT, BUY_CLOSE_LIMIT, BUY_OPEN_LIMIT_MAKER, BUY_CLOSE_LIMIT_MAKER, BUY_OPEN_MARKET:
		return true
	case SELL_OPEN_LIMIT, SELL_CLOSE_LIMIT, SELL_OPEN_LIMIT_MAKER, SELL_CLOSE_LIMIT_MAKER, SELL_OPEN_MARKET:
		return false
	default:
		return false
	}
}

func (s OrderMode) IsOpen() bool {
	switch s {
	case BUY_OPEN_LIMIT, SELL_OPEN_LIMIT, BUY_OPEN_LIMIT_MAKER, SELL_OPEN_LIMIT_MAKER, BUY_OPEN_MARKET, SELL_OPEN_MARKET:
		return true
	case BUY_CLOSE_LIMIT, SELL_CLOSE_LIMIT, BUY_CLOSE_LIMIT_MAKER, SELL_CLOSE_LIMIT_MAKER:
		return false
	default:
		return false
	}
}

func (s OrderMode) String() string {
	switch s {
	case BUY_OPEN_LIMIT:
		return "BUY_OPEN_LIMIT"
	case SELL_OPEN_LIMIT:
		return "SELL_OPEN_LIMIT"
	case BUY_CLOSE_LIMIT:
		return "BUY_CLOSE_LIMIT"
	case SELL_CLOSE_LIMIT:
		return "SELL_CLOSE_LIMIT"
	case BUY_OPEN_LIMIT_MAKER:
		return "BUY_OPEN_LIMIT_MAKER"
	case SELL_OPEN_LIMIT_MAKER:
		return "SELL_OPEN_LIMIT_MAKER"
	case BUY_CLOSE_LIMIT_MAKER:
		return "BUY_CLOSE_LIMIT_MAKER"
	case SELL_CLOSE_LIMIT_MAKER:
		return "SELL_CLOSE_LIMIT_MAKER"
	case BUY_OPEN_MARKET:
		return "BUY_OPEN_MARKET"
	case SELL_OPEN_MARKET:
		return "SELL_OPEN_MARKET"
	default:
		return "ERROR"
	}
}
