// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/toUpbit/v1/toUpbitParam.proto

package params

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_SERVING     HealthCheckResponse_Status = 0
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_Status = 1
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "SERVING",
		1: "NOT_SERVING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"SERVING":     0,
		"NOT_SERVING": 1,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_toUpbit_v1_params_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_api_toUpbit_v1_params_proto_enumTypes[0]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_toUpbit_v1_params_proto_rawDescGZIP(), []int{2, 0}
}

// ===== Requests =====
type ParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketCapM    float64                `protobuf:"fixed64,1,opt,name=market_cap_m,json=marketCapM,proto3" json:"market_cap_m,omitempty"`
	IsMeme        bool                   `protobuf:"varint,2,opt,name=is_meme,json=isMeme,proto3" json:"is_meme,omitempty"`
	SymbolName    string                 `protobuf:"bytes,3,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsRequest) Reset() {
	*x = ParamsRequest{}
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsRequest) ProtoMessage() {}

func (x *ParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsRequest.ProtoReflect.Descriptor instead.
func (*ParamsRequest) Descriptor() ([]byte, []int) {
	return file_api_toUpbit_v1_params_proto_rawDescGZIP(), []int{0}
}

func (x *ParamsRequest) GetMarketCapM() float64 {
	if x != nil {
		return x.MarketCapM
	}
	return 0
}

func (x *ParamsRequest) GetIsMeme() bool {
	if x != nil {
		return x.IsMeme
	}
	return false
}

func (x *ParamsRequest) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_toUpbit_v1_params_proto_rawDescGZIP(), []int{1}
}

// ===== Health =====
type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=toUpbitParam.HealthCheckResponse_Status" json:"status,omitempty"`
	Detail        string                     `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_toUpbit_v1_params_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING
}

func (x *HealthCheckResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// ===== Payload you want: {"fields":[ { "key": "...", "value": { "string_value": "..."} | {"number_value": 0} | {"bool_value": true}} ]} =====
type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*FieldValue_StringValue
	//	*FieldValue_NumberValue
	//	*FieldValue_BoolValue
	Value         isFieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_api_toUpbit_v1_params_proto_rawDescGZIP(), []int{3}
}

func (x *FieldValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FieldValue) GetValue() isFieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FieldValue) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isFieldValue_Value interface {
	isFieldValue_Value()
}

type FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FieldValue_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*FieldValue_StringValue) isFieldValue_Value() {}

func (*FieldValue_NumberValue) isFieldValue_Value() {}

func (*FieldValue_BoolValue) isFieldValue_Value() {}

type ParamsJsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*FieldValue          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsJsonResponse) Reset() {
	*x = ParamsJsonResponse{}
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsJsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsJsonResponse) ProtoMessage() {}

func (x *ParamsJsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_toUpbit_v1_params_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsJsonResponse.ProtoReflect.Descriptor instead.
func (*ParamsJsonResponse) Descriptor() ([]byte, []int) {
	return file_api_toUpbit_v1_params_proto_rawDescGZIP(), []int{4}
}

func (x *ParamsJsonResponse) GetData() []*FieldValue {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_toUpbit_v1_params_proto protoreflect.FileDescriptor

const file_api_toUpbit_v1_params_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/toUpbit/v1/toUpbitParam.proto\x12\x06params\"k\n" +
	"\rParamsRequest\x12 \n" +
	"\fmarket_cap_m\x18\x01 \x01(\x01R\n" +
	"marketCapM\x12\x17\n" +
	"\ais_meme\x18\x02 \x01(\bR\x06isMeme\x12\x1f\n" +
	"\vsymbol_name\x18\x03 \x01(\tR\n" +
	"symbolName\"\x14\n" +
	"\x12HealthCheckRequest\"\x91\x01\n" +
	"\x13HealthCheckResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".toUpbitParam.HealthCheckResponse.StatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"&\n" +
	"\x06Status\x12\v\n" +
	"\aSERVING\x10\x00\x12\x0f\n" +
	"\vNOT_SERVING\x10\x01\"\x92\x01\n" +
	"\n" +
	"FieldValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x03 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"<\n" +
	"\x12ParamsJsonResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.toUpbitParam.FieldValueR\x04data2\x97\x01\n" +
	"\rParamsService\x12>\n" +
	"\tGetParams\x12\x15.toUpbitParam.ParamsRequest\x1a\x1a.toUpbitParam.ParamsJsonResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.toUpbitParam.HealthCheckRequest\x1a\x1b.toUpbitParam.HealthCheckResponseB\n" +
	"Z\b.;paramsb\x06proto3"

var (
	file_api_toUpbit_v1_params_proto_rawDescOnce sync.Once
	file_api_toUpbit_v1_params_proto_rawDescData []byte
)

func file_api_toUpbit_v1_params_proto_rawDescGZIP() []byte {
	file_api_toUpbit_v1_params_proto_rawDescOnce.Do(func() {
		file_api_toUpbit_v1_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_toUpbit_v1_params_proto_rawDesc), len(file_api_toUpbit_v1_params_proto_rawDesc)))
	})
	return file_api_toUpbit_v1_params_proto_rawDescData
}

var file_api_toUpbit_v1_params_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_toUpbit_v1_params_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_toUpbit_v1_params_proto_goTypes = []any{
	(HealthCheckResponse_Status)(0), // 0: toUpbitParam.HealthCheckResponse.Status
	(*ParamsRequest)(nil),           // 1: toUpbitParam.ParamsRequest
	(*HealthCheckRequest)(nil),      // 2: toUpbitParam.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 3: toUpbitParam.HealthCheckResponse
	(*FieldValue)(nil),              // 4: toUpbitParam.FieldValue
	(*ParamsJsonResponse)(nil),      // 5: toUpbitParam.ParamsJsonResponse
}
var file_api_toUpbit_v1_params_proto_depIdxs = []int32{
	0, // 0: toUpbitParam.HealthCheckResponse.status:type_name -> toUpbitParam.HealthCheckResponse.Status
	4, // 1: toUpbitParam.ParamsJsonResponse.data:type_name -> toUpbitParam.FieldValue
	1, // 2: toUpbitParam.ParamsService.GetParams:input_type -> toUpbitParam.ParamsRequest
	2, // 3: toUpbitParam.ParamsService.HealthCheck:input_type -> toUpbitParam.HealthCheckRequest
	5, // 4: toUpbitParam.ParamsService.GetParams:output_type -> toUpbitParam.ParamsJsonResponse
	3, // 5: toUpbitParam.ParamsService.HealthCheck:output_type -> toUpbitParam.HealthCheckResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_toUpbit_v1_params_proto_init() }
func file_api_toUpbit_v1_params_proto_init() {
	if File_api_toUpbit_v1_params_proto != nil {
		return
	}
	file_api_toUpbit_v1_params_proto_msgTypes[3].OneofWrappers = []any{
		(*FieldValue_StringValue)(nil),
		(*FieldValue_NumberValue)(nil),
		(*FieldValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_toUpbit_v1_params_proto_rawDesc), len(file_api_toUpbit_v1_params_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_toUpbit_v1_params_proto_goTypes,
		DependencyIndexes: file_api_toUpbit_v1_params_proto_depIdxs,
		EnumInfos:         file_api_toUpbit_v1_params_proto_enumTypes,
		MessageInfos:      file_api_toUpbit_v1_params_proto_msgTypes,
	}.Build()
	File_api_toUpbit_v1_params_proto = out.File
	file_api_toUpbit_v1_params_proto_goTypes = nil
	file_api_toUpbit_v1_params_proto_depIdxs = nil
}
