// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/toUpbit/v1/params.proto

package params

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParamsService_GetParams_FullMethodName   = "/params.ParamsService/GetParams"
	ParamsService_HealthCheck_FullMethodName = "/params.ParamsService/HealthCheck"
)

// ParamsServiceClient is the client API for ParamsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===== Service =====
type ParamsServiceClient interface {
	GetParams(ctx context.Context, in *ParamsRequest, opts ...grpc.CallOption) (*ParamsJsonResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type paramsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParamsServiceClient(cc grpc.ClientConnInterface) ParamsServiceClient {
	return &paramsServiceClient{cc}
}

func (c *paramsServiceClient) GetParams(ctx context.Context, in *ParamsRequest, opts ...grpc.CallOption) (*ParamsJsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamsJsonResponse)
	err := c.cc.Invoke(ctx, ParamsService_GetParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paramsServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ParamsService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParamsServiceServer is the server API for ParamsService service.
// All implementations must embed UnimplementedParamsServiceServer
// for forward compatibility.
//
// ===== Service =====
type ParamsServiceServer interface {
	GetParams(context.Context, *ParamsRequest) (*ParamsJsonResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedParamsServiceServer()
}

// UnimplementedParamsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParamsServiceServer struct{}

func (UnimplementedParamsServiceServer) GetParams(context.Context, *ParamsRequest) (*ParamsJsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParams not implemented")
}
func (UnimplementedParamsServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedParamsServiceServer) mustEmbedUnimplementedParamsServiceServer() {}
func (UnimplementedParamsServiceServer) testEmbeddedByValue()                       {}

// UnsafeParamsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParamsServiceServer will
// result in compilation errors.
type UnsafeParamsServiceServer interface {
	mustEmbedUnimplementedParamsServiceServer()
}

func RegisterParamsServiceServer(s grpc.ServiceRegistrar, srv ParamsServiceServer) {
	// If the following call pancis, it indicates UnimplementedParamsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParamsService_ServiceDesc, srv)
}

func _ParamsService_GetParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParamsServiceServer).GetParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParamsService_GetParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParamsServiceServer).GetParams(ctx, req.(*ParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParamsService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParamsServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParamsService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParamsServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParamsService_ServiceDesc is the grpc.ServiceDesc for ParamsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParamsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "params.ParamsService",
	HandlerType: (*ParamsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetParams",
			Handler:    _ParamsService_GetParams_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ParamsService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/toUpbit/v1/params.proto",
}
